<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-PR5REPSJ" failures="1" tests="10" name="com.RunnerClass.SwagRunner" time="12.344" errors="0" timestamp="2024-08-23T23:50:23 IST" skipped="0">
  <testcase classname="com.RunnerClass.SwagRunner" name="LoginTest" time="0.873">
    <failure message="expected [Swag Labs ] but found [Swag Labs]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Swag Labs ] but found [Swag Labs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.BaseClass.BaseClass.validation(BaseClass.java:292)
at com.pom.SwagLogin.validLogIn(SwagLogin.java:53)
at com.RunnerClass.SwagRunner.LoginTest(SwagRunner.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="emptyUserEmptyPassLogin" time="0.248"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="validmailEmptyPass" time="0.259"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="validmailInvalidPass" time="0.257"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="invaldMailinvalidPass" time="0.175"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="productOneLogin" time="1.703"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="productTwoLogin" time="1.841"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="productThreeLogin" time="2.299"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="productFourLogin" time="2.384"/>
  <system-out/>
  <testcase classname="com.RunnerClass.SwagRunner" name="productFiveLogin" time="2.305"/>
  <system-out/>
</testsuite> <!-- com.RunnerClass.SwagRunner -->
